volumes:
  mysql-db:

services:
  app:
    container_name: app
    image: app:1.0.0
    build: 
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      app-db:
        condition: service_healthy
  app-db:
    container_name: app-db
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
  reverse_proxy:
    container_name: reverse_proxy
    image: reverse_proxy:1.0.0
    restart: always
    depends_on:
      - app
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

